@host = https://123.456.789.0
@token =

###
POST {{host}}/login/admin_client HTTP/1.1
Content-Type: application/json

{
    "admin_client_id": "admin",
    "password": "password"
}

###
POST {{host}}/camera_clients/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "camera_client_id": "camera1",
    "password": "camera1",
    "camera_id": 1,
    "view_id": 1
}

