""" add image_id to person_features table

Revision ID: 7561aa3bcbc9
Revises: dd74778265e7
Create Date: 2025-11-16 12:19:38.603797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7561aa3bcbc9'
down_revision: Union[str, Sequence[str], None] = 'dd74778265e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_features', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'person_features', 'person_image_paths', ['image_id'], ['image_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('', 'person_features', type_='foreignkey')
    op.drop_column('person_features', 'image_id')
    # ### end Alembic commands ###
