"""add person snapshots table

Revision ID: a5db485ccd29
Revises: 7561aa3bcbc9
Create Date: 2025-11-29 05:46:12.422242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a5db485ccd29'
down_revision: Union[str, Sequence[str], None] = '7561aa3bcbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('feature', pgvector.sqlalchemy.vector.VECTOR(dim=1280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_snapshots')
    # ### end Alembic commands ###
