"""add person_features table

Revision ID: d643ad1836fc
Revises: 179b25a76130
Create Date: 2025-11-08 06:33:57.032407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd643ad1836fc'
down_revision: Union[str, Sequence[str], None] = '179b25a76130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_features',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('feature', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1280), nullable=True),
                    sa.Column('camera_id', sa.Integer(), nullable=True),
                    sa.Column('view_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_features')
    # ### end Alembic commands ###
