""" add person_id to person_features table

Revision ID: 1b2857e2e73b
Revises: d643ad1836fc
Create Date: 2025-11-15 06:19:52.435786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2857e2e73b'
down_revision: Union[str, Sequence[str], None] = 'd643ad1836fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_features', sa.Column('person_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_features', 'person_id')
    # ### end Alembic commands ###
